"""ajoute comment model

Revision ID: 8cd08b438585
Revises: 260d89ef4520
Create Date: 2023-08-31 20:00:45.118451

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8cd08b438585'
down_revision = '260d89ef4520'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('blog_comments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('created', sa.DateTime(), nullable=True),
    sa.Column('online', sa.Boolean(), nullable=True),
    sa.Column('posts', sa.Integer(), nullable=True),
    sa.Column('authors', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['authors'], ['account_users.id'], ),
    sa.ForeignKeyConstraint(['posts'], ['blog_posts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('blog_comments')
    # ### end Alembic commands ###
