"""ajoute champ illustration au model post

Revision ID: a3e22dd7b05c
Revises: 8cd08b438585
Create Date: 2023-09-01 12:13:28.765390

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a3e22dd7b05c'
down_revision = '8cd08b438585'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('blog_posts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('illustration', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('blog_posts', schema=None) as batch_op:
        batch_op.drop_column('illustration')

    # ### end Alembic commands ###
