"""categories table

Revision ID: df710f19bead
Revises: f9ffdb27e950
Create Date: 2023-08-23 19:07:09.399888

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'df710f19bead'
down_revision = 'f9ffdb27e950'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('blog_categories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=16), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('blog_posts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('categories', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'blog_categories', ['categories'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('blog_posts', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('categories')

    op.drop_table('blog_categories')
    # ### end Alembic commands ###
