"""add password for user model

Revision ID: e1251ff009c7
Revises: a3e22dd7b05c
Create Date: 2023-09-13 13:03:01.736382

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e1251ff009c7'
down_revision = 'a3e22dd7b05c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('account_users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('password', sa.String(length=32), nullable=True))
        batch_op.create_unique_constraint(None, ['username'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('account_users', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('password')

    # ### end Alembic commands ###
