"""post table add fields

Revision ID: f9ffdb27e950
Revises: e8347b4f03e8
Create Date: 2023-08-23 18:50:33.986616

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f9ffdb27e950'
down_revision = 'e8347b4f03e8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('blog_posts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('slug', sa.String(length=128), nullable=True))
        batch_op.add_column(sa.Column('created', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('updated', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('online', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('blog_posts', schema=None) as batch_op:
        batch_op.drop_column('online')
        batch_op.drop_column('updated')
        batch_op.drop_column('created')
        batch_op.drop_column('slug')

    # ### end Alembic commands ###
